app:
  root_path: /private/data/projects/github.com/lupguo/copilot_develop
  openai_proxy:
    auth_token: "Your OpenAI-Token"
    socks_url: "socks5://127.0.0.1:10553"
  blog_summary:
    ai_prompt_file: ./prompt.yaml
    sqlite_db_file: ./data/blog_summary.db